#!/bin/bash
# Copy nvim config to build context.
cp -r /home/k/projects/linux_setup/configs/home/k/.config/nvim/ ./proj/

docker build -t lfni \
	--build-arg USER_ID=$(id -u) \
	--build-arg GROUP_ID=$(id -g) ./
